/**
 * Telemetry transport evidence beside metrics folded from saved runs.
 * A live daemon heartbeat or an empty spool is not a platform receipt.
 * @example
 * <Metrics events={events} state={state} arms={arms} busy={busy} onAction={act} boardUrl={url} />
 */
import { useState } from "react";
import type { Arms, State, TimelineEvent } from "../api";
import { deskHref } from "../route";
import { ago, latency, modelLabel } from "../format";
import { daemonDelivery } from "../metricsEvidence";
import { Fold } from "./Fold";
import { SlideOut } from "./SlideOut";

export function Metrics({ events, state, arms, busy, onAction, boardUrl, ticketId }: { events: TimelineEvent[]; state: State | null; arms: Arms | null; busy: string | null; onAction: (action: string, body?: Record<string, unknown>) => void; boardUrl?: string; ticketId: string | null }) {
  const [baseline, setBaseline] = useState<{ at: string; counts: Record<string, number> } | null>(null);
  const [detail, setDetail] = useState<string | null>(null);
  const [probe, setProbe] = useState<{ at: string; host: string } | null>(null);
  const rows = arms?.arms.filter((a) => a.tag === "support.reply") ?? [];
  const eu = state?.hosts.find((h) => h.kind === "daemon");
  const delivery = daemonDelivery(events, eu);
  const hosts = state ? [{ id: state.host.hostId, title: "US desk", status: state.host.status, health: state.host.healthz, written: state.host.status.lastSyncAt }, ...(eu ? [{ id: eu.hostId, title: "Europe daemon", status: eu.status, health: eu.healthz, written: eu.writtenAt }] : [])] : [];
  const picked = hosts.find((h) => h.id === detail);
  const asleep = eu?.powerView && eu.powerView.phase !== "awake";
  return <section className="evidence-page">
    <header className="page-heading"><div><h2 className="section-title">Metrics delivery</h2><p className="muted">Saved replies → SDK observations → daemon upload → AirPrompter.</p></div>{boardUrl ? <a className="external-link" href={`${boardUrl}/metrics`} target="_blank" rel="noreferrer">AirPrompter metrics ↗</a> : null}</header>
    <p className="fine muted">In AirPrompter, select {state?.airprompter.environment === "dev" ? "Development" : state?.airprompter.environment ?? "the matching environment"}, Support reply and Last 24 hours. Compare the same version before and after the test.</p>
    <section className="record-list" aria-label="Metrics transport"><div className="record-list-head"><h2>Delivery path</h2><button type="button" className="chip-button" disabled={busy !== null || !eu || !!asleep || !state?.features?.hostCli} onClick={() => onAction("host_cli", {command:"status"})}>Check daemon delivery</button></div>{hosts.map((h) => <button key={h.id} type="button" className="record-row" onClick={() => setDetail(h.id)}><span><strong>{h.title} · {h.health.telemetry?.uploadedBy === "daemon" ? `daemon ${h.health.telemetry.daemon ?? "unreported"}` : h.status.telemetry?.sink === "memory" ? "uploaded at invocation end" : "uploader unreported"}</strong><small>{(h.id === eu?.hostId ? delivery?.lastUploadAt : h.health.lastUploadAt) ? `Last reported upload ${ago(h.id === eu?.hostId ? delivery!.lastUploadAt! : h.health.lastUploadAt)}` : "No upload time reported"} · {h.status.spool?.depthSegments ?? "—"} queued segments · report {h.written ? ago(h.written) : "unreported"}</small></span><span className="record-open">Details →</span></button>)}</section>
    {delivery ? <p className="storage-note">Daemon status checked {ago(delivery.readAt)}: {delivery.sent ?? "—"} acknowledged segments · {delivery.quarantined ?? "—"} quarantined · {delivery.dropped ?? "—"} dropped · {delivery.queued ?? "—"} queued. Upload interval {delivery.intervalSeconds ?? "—"} seconds. This acknowledgment is separate from AirPrompter’s visible metric totals.</p> : <p className="fine muted">Check daemon delivery to read its acknowledged upload count. Worker health does not report the daemon’s last upload time.</p>}
    <Fold title="Send a bounded metrics test"><p className="fine muted">Run the selected seed ticket once on Europe. Its real model observations enter the shared spool; the daemon uploads on its own interval. This uses one slot from the daily run limit. Confirm arrival in AirPrompter using the same prompt, version, environment and time range.</p><div className="button-row"><button type="button" className="button secondary" disabled={busy !== null || !eu || !ticketId || !!asleep || !!state?.frozen?.frozen || !state || state.cap.used >= state.cap.cap} onClick={() => { setProbe({at:new Date().toISOString(),host:eu!.hostId}); onAction("enqueue", {ticketId,host:eu!.hostId}); }}>Run {ticketId ?? "ticket"} through Europe</button><button type="button" className="chip-button" disabled={busy !== null || !state} onClick={() => onAction("upload")}>Flush US metrics</button></div>{asleep ? <p className="fine muted">Europe is {eu?.powerView?.label}. Wake it from Controls before testing.</p> : null}{probe ? <p className="storage-note">Test requested at {probe.at} for {probe.host}. A request is not proof of a completed run or upload; inspect the saved reply and platform metrics. <a href={deskHref("database", ticketId)}>View saved reply →</a></p> : null}</Fold>
    <section className="record-list"><div className="record-list-head"><h2>Zudocs reply measurements</h2><button type="button" className="chip-button" disabled={!arms} onClick={() => arms && setBaseline({ at: arms.readAt, counts: Object.fromEntries(rows.map((r) => [`${r.versionId}|${r.arm}|${r.model}`,r.runs])) })}>Capture baseline</button></div><div className="evidence-padding"><p className="fine muted">Last 24 hours of saved runs · read {arms ? ago(arms.readAt) : "pending"}. Each row is one reply version, model and A/B group.</p><div className="scroll-x"><table className="evidence-table"><thead><tr><th>Version / group</th><th>Model</th><th>Runs</th><th>Since baseline</th><th>Mean latency</th><th>Checks</th></tr></thead><tbody>{rows.map((r) => <tr key={`${r.versionId}|${r.arm}|${r.model}`}><td>{r.versionId} · {r.arm === "none" ? "published" : r.arm}</td><td>{modelLabel(r.model)}</td><td>{r.runs}</td><td>{baseline ? r.runs-(baseline.counts[`${r.versionId}|${r.arm}|${r.model}`]??0) : "—"}</td><td>{latency(r.latencyMeanMs)}</td><td>{r.checksPassed} pass · {r.checksFailed} fail</td></tr>)}</tbody></table></div>{!rows.length ? <p className="muted">No saved reply measurements in this window.</p> : null}{baseline ? <p className="fine muted">Baseline read at {baseline.at}. Counts can decrease as records leave the rolling 24-hour window.</p> : null}</div></section>
    <p className="storage-note">AirPrompter rolls up minute windows from all reporting instances; Zudocs counts its saved runs. Mean latency differs from p50/p95. An empty spool or a healthy daemon does not prove these exact records arrived.</p>
    {picked ? <SlideOut title={`${picked.title}: metrics transport`} onClose={() => setDetail(null)}><dl className="integration-settings"><div><dt>Uploader</dt><dd>{picked.health.telemetry?.uploadedBy ?? "Unreported"}</dd></div><div><dt>Daemon</dt><dd>{picked.health.telemetry?.daemon ?? "Not applicable / unreported"}</dd></div><div><dt>{picked.id === eu?.hostId ? "Daemon upload time (CLI)" : "Last upload reported"}</dt><dd>{picked.id === eu?.hostId ? delivery?.lastUploadAt ?? "Check daemon delivery" : picked.health.lastUploadAt ?? "Unreported"}</dd></div><div><dt>Retry held until</dt><dd>{picked.health.backoffUntil ?? "No hold reported"}</dd></div><div><dt>Queued segments</dt><dd>{picked.status.spool?.depthSegments ?? "Unreported"}</dd></div><div><dt>Queued bytes</dt><dd>{picked.status.spool?.depthBytes ?? "Unreported"}</dd></div></dl><p className="fine muted">Worker health comes from its SDK report; daemon upload time comes from the recorded CLI status check. The Europe daemon ships observations from both workers; it does not run the model or serve prompts.</p><Fold title="Technical report"><pre className="record-fields">{JSON.stringify({hostId:picked.id,writtenAt:picked.written,daemonDelivery:picked.id === eu?.hostId ? delivery : null,telemetry:picked.health.telemetry,lastUploadAt:picked.health.lastUploadAt,spool:picked.health.spool,backoffUntil:picked.health.backoffUntil},null,2)}</pre></Fold></SlideOut> : null}
  </section>;
}
